package dsd.cms.DCMSCorba;

/**
* dsd/cms/DCMSCorba/DCMSInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMSCorba.idl
* Thursday, July 1, 2021 12:05:51 AM IST
*/

public final class DCMSInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public dsd.cms.DCMSCorba.DCMSInterface value = null;

  public DCMSInterfaceHolder ()
  {
  }

  public DCMSInterfaceHolder (dsd.cms.DCMSCorba.DCMSInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dsd.cms.DCMSCorba.DCMSInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dsd.cms.DCMSCorba.DCMSInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dsd.cms.DCMSCorba.DCMSInterfaceHelper.type ();
  }

}
