package dsd.cms.DCMSCorba;


/**
* dsd/cms/DCMSCorba/DCMSInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMSCorba.idl
* Thursday, July 1, 2021 12:05:51 AM IST
*/

abstract public class DCMSInterfaceHelper
{
  private static String  _id = "IDL:dsd/cms/DCMSCorba/DCMSInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, dsd.cms.DCMSCorba.DCMSInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dsd.cms.DCMSCorba.DCMSInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (dsd.cms.DCMSCorba.DCMSInterfaceHelper.id (), "DCMSInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dsd.cms.DCMSCorba.DCMSInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DCMSInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dsd.cms.DCMSCorba.DCMSInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static dsd.cms.DCMSCorba.DCMSInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dsd.cms.DCMSCorba.DCMSInterface)
      return (dsd.cms.DCMSCorba.DCMSInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dsd.cms.DCMSCorba._DCMSInterfaceStub stub = new dsd.cms.DCMSCorba._DCMSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static dsd.cms.DCMSCorba.DCMSInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dsd.cms.DCMSCorba.DCMSInterface)
      return (dsd.cms.DCMSCorba.DCMSInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dsd.cms.DCMSCorba._DCMSInterfaceStub stub = new dsd.cms.DCMSCorba._DCMSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
