package dsd.cms.DCMSCorba;


/**
* dsd/cms/DCMSCorba/DCMSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMSCorba.idl
* Thursday, July 1, 2021 12:05:51 AM IST
*/

public interface DCMSInterface extends DCMSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMSInterface
