package dsd.cms.DCMSCorba;


/**
* dsd/cms/DCMSCorba/listRecordIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMSCorba.idl
* Thursday, July 1, 2021 12:05:51 AM IST
*/

public final class listRecordIDHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public listRecordIDHolder ()
  {
  }

  public listRecordIDHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dsd.cms.DCMSCorba.listRecordIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dsd.cms.DCMSCorba.listRecordIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dsd.cms.DCMSCorba.listRecordIDHelper.type ();
  }

}
